// AUTO-GENERATED. DO NOT EDIT.
// Generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

extension Target {
  public static var coreRepositoryDiff: Target {
    .core(
      implements: .repositoryDiff,
      factory: .init(
        destinations: .coreRepositoryDiffDestinations,
        bundlePrefix: .coreRepositoryDiffBundlePrefix,
        deploymentTargets: .coreRepositoryDiffDeploymentTargets,
        infoPlist: .coreRepositoryDiffInfoPlist,
        scripts: .coreRepositoryDiffTargetScripts,
        dependencies: .coreRepositoryDiffDependencies,
        settings: .coreRepositoryDiffSettings,
        coreDataModels: .coreRepositoryDiffCoreDataModels
      )
    )
  }
}

extension TargetReference {
  public static var coreRepositoryDiff: TargetReference {
    .core(
      implements: .repositoryDiff
    )
  }
}
