// AUTO-GENERATED. DO NOT EDIT.
// Generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

extension Target {
  public static var coreRepositoryUI: Target {
    .core(
      implements: .repositoryUI,
      factory: .init(
        destinations: .coreRepositoryUIDestinations,
        bundlePrefix: .coreRepositoryUIBundlePrefix,
        deploymentTargets: .coreRepositoryUIDeploymentTargets,
        infoPlist: .coreRepositoryUIInfoPlist,
        scripts: .coreRepositoryUITargetScripts,
        dependencies: .coreRepositoryUIDependencies,
        settings: .coreRepositoryUISettings,
        coreDataModels: .coreRepositoryUICoreDataModels
      )
    )
  }
}

extension TargetReference {
  public static var coreRepositoryUI: TargetReference {
    .core(
      implements: .repositoryUI
    )
  }
}
