// AUTO-GENERATED. DO NOT EDIT.
// Generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

extension Target {
  public static var featureRepositoryOperations: Target {
    .feature(
      implements: .repositoryOperations,
      factory: .init(
        destinations: .featureRepositoryOperationsDestinations,
        bundlePrefix: .featureRepositoryOperationsBundlePrefix,
        deploymentTargets: .featureRepositoryOperationsDeploymentTargets,
        infoPlist: .featureRepositoryOperationsInfoPlist,
        scripts: .featureRepositoryOperationsTargetScripts,
        dependencies: .featureRepositoryOperationsDependencies,
        settings: .featureRepositoryOperationsSettings,
        coreDataModels: .featureRepositoryOperationsCoreDataModels
      )
    )
  }
}

extension TargetReference {
  public static var featureRepositoryOperations: TargetReference {
    .feature(
      implements: .repositoryOperations
    )
  }
}
