// AUTO-GENERATED. DO NOT EDIT.
// Generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

extension Target {
  public static var featureRepositoryUI: Target {
    .feature(
      implements: .repositoryUI,
      factory: .init(
        destinations: .featureRepositoryUIDestinations,
        bundlePrefix: .featureRepositoryUIBundlePrefix,
        deploymentTargets: .featureRepositoryUIDeploymentTargets,
        infoPlist: .featureRepositoryUIInfoPlist,
        scripts: .featureRepositoryUITargetScripts,
        dependencies: .featureRepositoryUIDependencies,
        settings: .featureRepositoryUISettings,
        coreDataModels: .featureRepositoryUICoreDataModels
      )
    )
  }
}

extension TargetReference {
  public static var featureRepositoryUI: TargetReference {
    .feature(
      implements: .repositoryUI
    )
  }
}
