// AUTO-GENERATED. DO NOT EDIT.
// Generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

extension Target {
  public static var featureRepositoryOperations: Target {
    .feature(
      implements: .repositoryOperations,
      factory: .init(
        destinations: .featureRepositoryOperationsDestinations,
        bundlePrefix: .featureRepositoryOperationsBundlePrefix,
        deploymentTargets: .featureRepositoryOperationsDeploymentTargets,
        infoPlist: .featureRepositoryOperationsInfoPlist,
        scripts: .featureRepositoryOperationsTargetScripts,
        dependencies: .featureRepositoryOperationsDependencies,
        settings: .featureRepositoryOperationsSettings,
        coreDataModels: .featureRepositoryOperationsCoreDataModels
      )
    )
  }

  public static var featureRepositoryOperationsTests: Target {
    .feature(
      tests: .repositoryOperations,
      factory: .init(
        destinations: .featureRepositoryOperationsTestsDestinations,
        bundlePrefix: .featureRepositoryOperationsTestsBundlePrefix,
        deploymentTargets: .featureRepositoryOperationsTestsDeploymentTargets,
        infoPlist: .featureRepositoryOperationsTestsInfoPlist,
        scripts: .featureRepositoryOperationsTestsTargetScripts,
        dependencies: .featureRepositoryOperationsTestsDependencies,
        settings: .featureRepositoryOperationsTestsSettings,
        coreDataModels: .featureRepositoryOperationsTestsCoreDataModels
      )
    )
  }
}

extension TargetReference {
  public static var featureRepositoryOperations: TargetReference {
    .feature(
      implements: .repositoryOperations
    )
  }

  public static var featureRepositoryOperationsTests: TargetReference {
    .feature(
      tests: .repositoryOperations
    )
  }
}
