// AUTO-GENERATED. DO NOT EDIT.
// Generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

extension Target {
  public static var featureRepositoryDiff: Target {
    .feature(
      implements: .repositoryDiff,
      factory: .init(
        destinations: .featureRepositoryDiffDestinations,
        bundlePrefix: .featureRepositoryDiffBundlePrefix,
        deploymentTargets: .featureRepositoryDiffDeploymentTargets,
        infoPlist: .featureRepositoryDiffInfoPlist,
        scripts: .featureRepositoryDiffTargetScripts,
        dependencies: .featureRepositoryDiffDependencies,
        settings: .featureRepositoryDiffSettings,
        coreDataModels: .featureRepositoryDiffCoreDataModels
      )
    )
  }
}

extension TargetReference {
  public static var featureRepositoryDiff: TargetReference {
    .feature(
      implements: .repositoryDiff
    )
  }
}
