// AUTO-GENERATED. DO NOT EDIT.
// Generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

extension Target {
  public static var featureRepositoryHistory: Target {
    .feature(
      implements: .repositoryHistory,
      factory: .init(
        destinations: .featureRepositoryHistoryDestinations,
        bundlePrefix: .featureRepositoryHistoryBundlePrefix,
        deploymentTargets: .featureRepositoryHistoryDeploymentTargets,
        infoPlist: .featureRepositoryHistoryInfoPlist,
        scripts: .featureRepositoryHistoryTargetScripts,
        dependencies: .featureRepositoryHistoryDependencies,
        settings: .featureRepositoryHistorySettings,
        coreDataModels: .featureRepositoryHistoryCoreDataModels
      )
    )
  }

  public static var featureRepositoryHistoryTests: Target {
    .feature(
      tests: .repositoryHistory,
      factory: .init(
        destinations: .featureRepositoryHistoryTestsDestinations,
        bundlePrefix: .featureRepositoryHistoryTestsBundlePrefix,
        deploymentTargets: .featureRepositoryHistoryTestsDeploymentTargets,
        infoPlist: .featureRepositoryHistoryTestsInfoPlist,
        scripts: .featureRepositoryHistoryTestsTargetScripts,
        dependencies: .featureRepositoryHistoryTestsDependencies,
        settings: .featureRepositoryHistoryTestsSettings,
        coreDataModels: .featureRepositoryHistoryTestsCoreDataModels
      )
    )
  }
}

extension TargetReference {
  public static var featureRepositoryHistory: TargetReference {
    .feature(
      implements: .repositoryHistory
    )
  }

  public static var featureRepositoryHistoryTests: TargetReference {
    .feature(
      tests: .repositoryHistory
    )
  }
}
