// AUTO-GENERATED. DO NOT EDIT.
// Generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

extension Target {
  public static var featureRepositoryChanges: Target {
    .feature(
      implements: .repositoryChanges,
      factory: .init(
        destinations: .featureRepositoryChangesDestinations,
        bundlePrefix: .featureRepositoryChangesBundlePrefix,
        deploymentTargets: .featureRepositoryChangesDeploymentTargets,
        infoPlist: .featureRepositoryChangesInfoPlist,
        scripts: .featureRepositoryChangesTargetScripts,
        dependencies: .featureRepositoryChangesDependencies,
        settings: .featureRepositoryChangesSettings,
        coreDataModels: .featureRepositoryChangesCoreDataModels
      )
    )
  }

  public static var featureRepositoryChangesTests: Target {
    .feature(
      tests: .repositoryChanges,
      factory: .init(
        destinations: .featureRepositoryChangesTestsDestinations,
        bundlePrefix: .featureRepositoryChangesTestsBundlePrefix,
        deploymentTargets: .featureRepositoryChangesTestsDeploymentTargets,
        infoPlist: .featureRepositoryChangesTestsInfoPlist,
        scripts: .featureRepositoryChangesTestsTargetScripts,
        dependencies: .featureRepositoryChangesTestsDependencies,
        settings: .featureRepositoryChangesTestsSettings,
        coreDataModels: .featureRepositoryChangesTestsCoreDataModels
      )
    )
  }
}

extension TargetReference {
  public static var featureRepositoryChanges: TargetReference {
    .feature(
      implements: .repositoryChanges
    )
  }

  public static var featureRepositoryChangesTests: TargetReference {
    .feature(
      tests: .repositoryChanges
    )
  }
}
