// AUTO-GENERATED. DO NOT EDIT.
// Generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

extension Target {
  public static var coreRepositoryDiff: Target {
    .core(
      implements: .repositoryDiff,
      factory: .init(
        destinations: .coreRepositoryDiffDestinations,
        bundlePrefix: .coreRepositoryDiffBundlePrefix,
        deploymentTargets: .coreRepositoryDiffDeploymentTargets,
        infoPlist: .coreRepositoryDiffInfoPlist,
        scripts: .coreRepositoryDiffTargetScripts,
        dependencies: .coreRepositoryDiffDependencies,
        settings: .coreRepositoryDiffSettings,
        coreDataModels: .coreRepositoryDiffCoreDataModels
      )
    )
  }

  public static var coreRepositoryDiffTests: Target {
    .core(
      tests: .repositoryDiff,
      factory: .init(
        destinations: .coreRepositoryDiffTestsDestinations,
        bundlePrefix: .coreRepositoryDiffTestsBundlePrefix,
        deploymentTargets: .coreRepositoryDiffTestsDeploymentTargets,
        infoPlist: .coreRepositoryDiffTestsInfoPlist,
        scripts: .coreRepositoryDiffTestsTargetScripts,
        dependencies: .coreRepositoryDiffTestsDependencies,
        settings: .coreRepositoryDiffTestsSettings,
        coreDataModels: .coreRepositoryDiffTestsCoreDataModels
      )
    )
  }
}

extension TargetReference {
  public static var coreRepositoryDiff: TargetReference {
    .core(
      implements: .repositoryDiff
    )
  }

  public static var coreRepositoryDiffTests: TargetReference {
    .core(
      tests: .repositoryDiff
    )
  }
}
