// AUTO-GENERATED. DO NOT EDIT.
// Generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

extension Target {
  public static var featureRepositoryChanges: Target {
    .feature(
      implements: .repositoryChanges,
      factory: .init(
        destinations: .featureRepositoryChangesDestinations,
        bundlePrefix: .featureRepositoryChangesBundlePrefix,
        deploymentTargets: .featureRepositoryChangesDeploymentTargets,
        infoPlist: .featureRepositoryChangesInfoPlist,
        scripts: .featureRepositoryChangesTargetScripts,
        dependencies: .featureRepositoryChangesDependencies,
        settings: .featureRepositoryChangesSettings,
        coreDataModels: .featureRepositoryChangesCoreDataModels
      )
    )
  }
}

extension TargetReference {
  public static var featureRepositoryChanges: TargetReference {
    .feature(
      implements: .repositoryChanges
    )
  }
}
