// AUTO-GENERATED. DO NOT EDIT.
// Generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

extension Target {
  public static var coreGitCredential: Target {
    .core(
      implements: .gitCredential,
      factory: .init(
        destinations: .coreGitCredentialDestinations,
        bundlePrefix: .coreGitCredentialBundlePrefix,
        deploymentTargets: .coreGitCredentialDeploymentTargets,
        infoPlist: .coreGitCredentialInfoPlist,
        scripts: .coreGitCredentialTargetScripts,
        dependencies: .coreGitCredentialDependencies,
        settings: .coreGitCredentialSettings,
        coreDataModels: .coreGitCredentialCoreDataModels
      )
    )
  }

  public static var coreGitCredentialTests: Target {
    .core(
      tests: .gitCredential,
      factory: .init(
        destinations: .coreGitCredentialTestsDestinations,
        bundlePrefix: .coreGitCredentialTestsBundlePrefix,
        deploymentTargets: .coreGitCredentialTestsDeploymentTargets,
        infoPlist: .coreGitCredentialTestsInfoPlist,
        scripts: .coreGitCredentialTestsTargetScripts,
        dependencies: .coreGitCredentialTestsDependencies,
        settings: .coreGitCredentialTestsSettings,
        coreDataModels: .coreGitCredentialTestsCoreDataModels
      )
    )
  }
}

extension TargetReference {
  public static var coreGitCredential: TargetReference {
    .core(
      implements: .gitCredential
    )
  }

  public static var coreGitCredentialTests: TargetReference {
    .core(
      tests: .gitCredential
    )
  }
}
