// AUTO-GENERATED. DO NOT EDIT.
// Generated by SyncTargets.swift
import Foundation
import ProjectDescription
import TargetPlugin

extension Target {
  public static var featureRepositoryTree: Target {
    .feature(
      implements: .repositoryTree,
      factory: .init(
        destinations: .featureRepositoryTreeDestinations,
        bundlePrefix: .featureRepositoryTreeBundlePrefix,
        deploymentTargets: .featureRepositoryTreeDeploymentTargets,
        infoPlist: .featureRepositoryTreeInfoPlist,
        scripts: .featureRepositoryTreeTargetScripts,
        dependencies: .featureRepositoryTreeDependencies,
        settings: .featureRepositoryTreeSettings,
        coreDataModels: .featureRepositoryTreeCoreDataModels
      )
    )
  }

  public static var featureRepositoryTreeTests: Target {
    .feature(
      tests: .repositoryTree,
      factory: .init(
        destinations: .featureRepositoryTreeTestsDestinations,
        bundlePrefix: .featureRepositoryTreeTestsBundlePrefix,
        deploymentTargets: .featureRepositoryTreeTestsDeploymentTargets,
        infoPlist: .featureRepositoryTreeTestsInfoPlist,
        scripts: .featureRepositoryTreeTestsTargetScripts,
        dependencies: .featureRepositoryTreeTestsDependencies,
        settings: .featureRepositoryTreeTestsSettings,
        coreDataModels: .featureRepositoryTreeTestsCoreDataModels
      )
    )
  }
}

extension TargetReference {
  public static var featureRepositoryTree: TargetReference {
    .feature(
      implements: .repositoryTree
    )
  }

  public static var featureRepositoryTreeTests: TargetReference {
    .feature(
      tests: .repositoryTree
    )
  }
}
